config/routes.rb
Exam20444367::Application.routes.draw do
  resources :saves

  resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  max_paginates_per 20

  class << self
    def save_to_disk
      employees = Employee.all
      fname = "#{Rails.root}/test.txt"
      File.open(fname,mode="a") do |f|
        employees.each do |e|
          f.puts e.name + " , " + e.hourly_rate.to_s
        end
      end
    end
     handle_asynchronously :save_to_disk
  end
end

app/models/save.rb
class Save < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def save_to_disk
    redirect_to action: :index
  end
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.page params[:page]
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :rate)
    end
end

app/controllers/saves_controller.rb
class SavesController < ApplicationController
  before_action :set_safe, only: [:show, :edit, :update, :destroy]


  def save_to_disk
    redirect_to action: "index"
  end
  # GET /saves
  # GET /saves.json

  def index
    @saves = Save.all
  end

  # GET /saves/1
  # GET /saves/1.json
  def show
  end

  # GET /saves/new
  def new
    @safe = Save.new
  end

  # GET /saves/1/edit
  def edit
  end

  # POST /saves
  # POST /saves.json
  def create
    @safe = Save.new(safe_params)

    respond_to do |format|
      if @safe.save
        format.html { redirect_to @safe, notice: 'Save was successfully created.' }
        format.json { render action: 'show', status: :created, location: @safe }
      else
        format.html { render action: 'new' }
        format.json { render json: @safe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saves/1
  # PATCH/PUT /saves/1.json
  def update
    respond_to do |format|
      if @safe.update(safe_params)
        format.html { redirect_to @safe, notice: 'Save was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @safe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saves/1
  # DELETE /saves/1.json
  def destroy
    @safe.destroy
    respond_to do |format|
      format.html { redirect_to saves_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_safe
      @safe = Save.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def safe_params
      params[:safe]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/saves_helper.rb
module SavesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
   	<div class="field">
  <label for ="hours_worked">Hours Worked</label><br/>
  <%= text_field_tag :hours_worked %>
</div>
    <div class="field">
      <p>Amount Owed</p>
      <%= text_field_tag :amount_owed %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= javascript_include_tag "employee" %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.rate %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
       <td><%= link_to 'Save', saves_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>
<%= paginate @employees %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/save_to_disk.html.erb
<h1>Save to Disk</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @employee.rate %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam20444367</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/saves/_form.html.erb
<%= form_for(@safe) do |f| %>
  <% if @safe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@safe.errors.count, "error") %> prohibited this safe from being saved:</h2>

      <ul>
      <% @safe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saves/edit.html.erb
<h1>Editing safe</h1>

<%= render 'form' %>

<%= link_to 'Show', @safe %> |
<%= link_to 'Back', saves_path %>

app/views/saves/index.html.erb
<h1>Listing saves</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @saves.each do |safe| %>
      <tr>
        <td><%= link_to 'Show', safe %></td>
        <td><%= link_to 'Edit', edit_safe_path(safe) %></td>
        <td><%= link_to 'Destroy', safe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Save', new_safe_path %>

app/views/saves/new.html.erb
<h1>New safe</h1>

<%= render 'form' %>

<%= link_to 'Back', saves_path %>

app/views/saves/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_safe_path(@safe) %> |
<%= link_to 'Back', saves_path %>